# Generated by Django 4.0.2 on 2022-05-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.BigIntegerField(null=True),
        ),
    ]
