# Generated by Django 4.0.2 on 2022-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='caption',
            field=models.CharField(default=None, max_length=22),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='photo',
            field=models.ImageField(default='/photo/img.png', height_field=500, upload_to='photo/', width_field=500),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
