# Generated by Django 4.0.2 on 2022-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='text',
            field=models.TextField(),
        ),
    ]
