# Generated by Django 4.0.2 on 2022-05-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
    ]
