# Generated by Django 4.0.2 on 2022-05-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_caption_news_category_news_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='like',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
