# Generated by Django 4.0.2 on 2022-03-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_mymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category'),
        ),
    ]
