# Generated by Django 4.0.2 on 2022-05-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_like_news_likes_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
