# Generated by Django 4.0.2 on 2022-03-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.mymodel'),
            preserve_default=False,
        ),
    ]
