# Generated by Django 4.0.2 on 2022-05-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created_at1',
        ),
    ]
