# Generated by Django 4.0.2 on 2022-05-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_created_at_news_created_at1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_at1',
            new_name='created_at',
        ),
    ]
