# Generated by Django 4.0.2 on 2022-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='Publications',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='donate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='subscribers',
            field=models.BigIntegerField(default=0),
        ),
    ]
